import assert from 'node:assert/strict';
import { seed, transition, reviewEvents, validStored } from '../app/projects.ts';
import { visiblePhotoSelection, togglePhotoSelection } from '../app/photo-selection-model.ts';
import { makeBackup, readBackup } from '../app/backup-model.ts';
const original=seed[0];
const first=transition(original,{type:'photo-review',index:1,note:'창가가 밝습니다.',resolved:false});
const done=transition(first,{type:'photo-review',index:1,note:'창가가 밝습니다.',resolved:true});
const again=transition(done,{type:'photo-review',index:1,note:'대비를 낮춰 주세요.',resolved:false});
assert.deepEqual(reviewEvents(again.photoReviews![0]).map(e=>[e.note,e.resolved]),[['대비를 낮춰 주세요.',false],['창가가 밝습니다.',true],['창가가 밝습니다.',false]]);
assert.equal(first.photoReviews![0].events!.length,1);
assert.equal(visiblePhotoSelection(first,1,true),1);
assert.equal(visiblePhotoSelection(done,1,true),null);
assert.equal(visiblePhotoSelection(first,0,true),null);
assert.equal(visiblePhotoSelection(first,null,false),null);
assert.equal(visiblePhotoSelection(first,50,false),null);
assert.equal(togglePhotoSelection(1,1),null);
assert.equal(togglePhotoSelection(null,1),1);
assert.equal(togglePhotoSelection(1,2),2);
assert.throws(()=>transition(first,{type:'photo-review',index:1,note:'다른 메모',resolved:true}));
const legacy={...original,photoReviews:[{index:0,note:'이전 완료 메모',resolved:true}]};
assert.deepEqual(reviewEvents(legacy.photoReviews[0]),[{note:'이전 완료 메모',resolved:true}]);
const migrated=transition(legacy,{type:'photo-review',index:0,note:'새 요청',resolved:false});
assert.equal(reviewEvents(migrated.photoReviews![0])[1].note,'이전 완료 메모');
const records=seed.map(p=>p.id===again.id?again:p);
assert.deepEqual(readBackup(makeBackup(records)),JSON.parse(JSON.stringify(records)));
assert.equal(validStored(seed.map(p=>p.id===legacy.id?legacy:p)),true);
assert.equal(validStored(seed.map(p=>p.id===again.id?{...again,photoReviews:[{...again.photoReviews![0],events:[{note:'bad',resolved:true,at:'bad date'}]}]}:p)),false);
let uploads=transition(seed[5],{type:'upload',files:[{name:'a',url:'data:image/png;base64,AA=='},{name:'b',url:'data:image/png;base64,AA=='}]});
uploads=transition({...uploads,stage:2},{type:'photo-review',index:1,note:'두 번째 사진',resolved:false});
uploads=transition({...uploads,stage:1},{type:'remove-uploads',indices:[0]});
assert.equal(uploads.photoReviews![0].index,0);
assert.equal(uploads.photoReviews![0].events![0].note,'두 번째 사진');
console.log('PASS · selection toggle/filter, repeated review history, legacy preservation, backup roundtrip, invalid history rejection, deletion remapping');
