import assert from 'node:assert/strict';
import { seed, transition, validStored, mergeWithSeed } from '../app/projects.ts';
import { boardColumns, defaultDetailTab, boardActions } from '../app/board-model.ts';
import { workspaceQueue, workspaceForStage, isWorkspaceView, metricDestinations, scheduleRows } from '../app/workspace-model.ts';
import { comparisonState } from '../app/comparison-model.ts';
let p = seed.find(p=>p.id===4)!;
p=transition(p,{type:'advance'});
assert.equal(p.stage,1);
assert.throws(()=>transition(p,{type:'advance'}));
p=transition(p,{type:'upload',files:[{name:'sample.png',url:'data:image/png;base64,AA=='}]});
assert.equal(p.photos,1);
assert.throws(()=>transition(p,{type:'advance'}));
p=transition(p,{type:'photo-category',index:0,category:'객실'});
assert.equal(p.uploads?.[0].category,'객실');
assert.equal(p.shots?.[0],true);
for(let index=0;index<4;index++)p=transition(p,{type:'shot',index,checked:true});
let deletion=transition(seed.find(p=>p.id===6)!,{type:'upload',files:[{name:'first.png',url:'data:image/png;base64,AA=='},{name:'second.png',url:'data:image/png;base64,BB=='}]});
deletion=transition(deletion,{type:'shot',index:0,checked:true});
deletion=transition(deletion,{type:'upload',files:[{name:'third.png',url:'data:image/png;base64,CC'}]});
deletion=transition(deletion,{type:'remove-uploads',indices:[0,2]});
assert.equal(deletion.photos,1);
assert.equal(deletion.uploads?.[0].name,'second.png');
assert.deepEqual(deletion.shots,[false,false,false,false]);
deletion=transition(deletion,{type:'remove-uploads',indices:[0]});
assert.equal(deletion.photos,0);
assert.throws(()=>transition(deletion,{type:'advance'}));
assert.throws(()=>transition(seed[0],{type:'remove-uploads',indices:[0]}));
assert.throws(()=>transition(seed[5],{type:'remove-uploads',indices:[]}));
p=transition(p,{type:'advance'});
assert.equal(p.stage,2);
p=transition(p,{type:'advance'});
assert.equal(p.stage,3);
assert.throws(()=>transition(p,{type:'reject',note:' '}));
p=transition(p,{type:'reject',note:'창가 노출 조정'});
assert.equal(p.stage,2);
assert.equal(p.note,'창가 노출 조정');
p=transition(p,{type:'advance'});
assert.equal(p.note,'');
p=transition(p,{type:'advance'});
assert.equal(p.stage,4);
for(let index=0;index<3;index++)p=transition(p,{type:'channel',index});
assert.equal(p.stage,5);
p=transition(p,{type:'channel',index:1});
assert.equal(p.stage,4);
assert.throws(()=>transition(p,{type:'channel',index:9}));
assert.throws(()=>transition(seed[0],{type:'channel',index:0}));
assert.throws(()=>transition(seed[0],{type:'schedule',date:'2026-09-07',due:'2026-09-06',time:'10:00',owner:'김서연'}));
assert.throws(()=>transition(seed[0],{type:'schedule',date:'2026-09-07',due:'2026-09-08',time:'29:00',owner:'김서연'}));
const scheduled=transition(seed[0],{type:'schedule',date:'2026-09-07',due:'2026-09-08',time:'10:00',owner:'박지훈'});
assert.equal(scheduled.owner,'박지훈');
assert.equal(scheduled.due,'2026-09-08');
assert.ok(validStored(seed));
assert.ok(!validStored([]));
assert.ok(!validStored(seed.map(x=>({...x,stage:9}))));
assert.equal(seed[0].stage,3);
console.log('PASS · entire pipeline, upload prerequisite, revision, approval, channel completion/undo, schedule validation, local storage validation, immutability');
const all = boardColumns(seed, 'all', '');
assert.equal(all.length, 6);
assert.equal(all.reduce((n,c)=>n+c.projects.length,0), seed.length);
const scheduledOnly = boardColumns(seed, '0', '');
assert.equal(scheduledOnly.length, 1);
assert.equal(scheduledOnly[0].projects.length, 2);
assert.ok(scheduledOnly[0].projects.every(p=>p.stage===0));
const searched = boardColumns(seed, 'all', '모먼트');
assert.equal(searched.reduce((n,c)=>n+c.projects.length,0), 1);
assert.equal(searched[1].projects[0].name, '모먼트 부산');
assert.deepEqual([0,1,2,3,4,5].map(defaultDetailTab), ['schedule','photos','photos','photos','channels','channels']);
assert.equal(boardActions[1].label,'사진 업로드');
assert.equal(boardActions[3].label,'사진 검수 · 승인');
assert.equal(boardColumns(seed,'all','검색결과없음').reduce((n,c)=>n+c.projects.length,0),0);
console.log('PASS · all stages, filtered columns and counts, search counts, stage-specific task labels and detail entry tabs');
assert.deepEqual([0,1,2,3,4,5].map(workspaceForStage),['schedule','upload','review','review','publish','publish']);
assert.ok(isWorkspaceView('upload'));
assert.ok(!isWorkspaceView('board'));
assert.ok(!isWorkspaceView('toString'));
assert.equal(workspaceQueue(seed,'schedule').length,2);
assert.equal(workspaceQueue(seed,'upload')[0].name,'모먼트 부산');
assert.equal(workspaceQueue(seed,'review').length,3);
assert.equal(workspaceQueue(seed,'review')[0].stage,3);
assert.equal(workspaceQueue(seed,'publish').length,4);
assert.equal(workspaceQueue(seed,'publish')[0].stage,4);
const moved=seed.map(p=>p.id===4?transition(p,{type:'advance'}):p);
assert.equal(workspaceQueue(moved,'schedule').length,1);
assert.equal(workspaceQueue(moved,'upload').length,2);
assert.equal(boardColumns(moved,'1','').at(0)?.projects.length,2);
console.log('PASS · four workflow menus, review priority, completed channel access, synchronized queues and board');
assert.deepEqual(comparisonState(0),{before:0,after:100,showBefore:false,showAfter:true});
assert.deepEqual(comparisonState(100),{before:100,after:0,showBefore:true,showAfter:false});
assert.deepEqual(comparisonState(50),{before:50,after:50,showBefore:true,showAfter:true});
assert.equal(comparisonState(-10).before,0);
assert.equal(comparisonState(120).before,100);
assert.equal(comparisonState(NaN).before,50);
assert.deepEqual(metricDestinations,[{view:'board',scope:'active'},{view:'board',scope:'week'},{view:'board',scope:'overdue'},{view:'board',scope:'5'}]);
assert.equal(boardColumns(seed,'active','').reduce((n,c)=>n+c.projects.length,0),7);
assert.equal(boardColumns(seed,'overdue','').reduce((n,c)=>n+c.projects.length,0),1);
assert.equal(boardColumns(seed,'week','').reduce((n,c)=>n+c.projects.length,0),6);
assert.equal(boardColumns(seed,'week','').length,6);
assert.equal(workspaceQueue(seed,'schedule','today').length,2);
assert.equal(workspaceQueue(seed,'review','3').length,2);
const future=seed.map(p=>p.id===4?{...p,date:'2026-09-05'}:p);
assert.equal(workspaceQueue(future,'schedule','today').length,1);
assert.equal(workspaceQueue(seed,'publish','5').length,3);
assert.equal(workspaceQueue([transition(seed[0],{type:'reject',note:'노출 수정'})],'review','3').length,0);
console.log('PASS · comparison endpoints, dashboard destinations, active/overdue/today/review filters, filtered handoff');
for(let stage=1;stage<=5;stage++){
 const source={...seed[0],stage,channels:stage>=4?[true,true,true]:[false,false,false],uploads:[{name:'keep.png',url:'data:image/png;base64,AA=='}],history:['기존 기록']};
 const back=transition(source,{type:'rollback',reason:'  누락 사진 추가  '});
 assert.equal(back.stage,stage-1);
 assert.deepEqual(back.uploads,source.uploads);
 assert.equal(back.photos,source.photos);
 assert.equal(back.date,source.date);
 assert.equal(back.note,source.note);
 assert.deepEqual(back.channels,[false,false,false]);
 assert.ok(back.history?.[0].includes('누락 사진 추가'));
 assert.equal(back.history?.[1],'기존 기록');
 assert.equal(source.stage,stage);
 assert.ok(validStored(seed.map(p=>p.id===source.id?back:p)));
 assert.throws(()=>transition(source,{type:'rollback',reason:'  '}));
}
assert.throws(()=>transition(seed[3],{type:'rollback',reason:'실수'}));
console.log('PASS · rollback all stages, required reason, retained data/history, cleared publishing checks, persistence');
let quality=transition(seed[0],{type:'photo-review',index:0,note:'창가 노출 조정',resolved:false});
assert.equal(quality.stage,2);
assert.ok(quality.recheck?.every(Boolean));
assert.throws(()=>transition(quality,{type:'advance'}));
quality=transition(quality,{type:'photo-review',index:0,note:'창가 노출 조정',resolved:true});
quality=transition(quality,{type:'advance'});
assert.equal(quality.stage,3);
quality=transition(quality,{type:'advance'});
quality=transition(quality,{type:'url',index:1,url:'https://www.instagram.com/p/demo/'});
assert.equal(quality.channelUrls?.[1],'https://www.instagram.com/p/demo/');
assert.equal(quality.recheck?.[1],true);
quality=transition(quality,{type:'channel',index:1});
assert.equal(quality.recheck?.[1],false);
quality=transition(quality,{type:'photo-review',index:1,note:'색온도 확인',resolved:false});
assert.equal(quality.stage,2);
assert.ok(quality.channels.every(v=>!v));
assert.equal(quality.channelUrls?.[1],'https://www.instagram.com/p/demo/');
assert.throws(()=>transition(quality,{type:'url',index:0,url:'javascript:alert(1)'}));
assert.throws(()=>transition(quality,{type:'url',index:0,url:'https://user:password@example.com'}));
assert.throws(()=>transition(quality,{type:'photo-review',index:99,note:'수정',resolved:false}));
assert.ok(validStored(seed.map(x=>x.id===quality.id?quality:x)));
assert.ok(!validStored(seed.map(x=>({...x,channelUrls:['javascript:alert(1)','','']}))));
const shotProject=transition(transition(seed[5],{type:'upload',files:[{name:'room.png',url:'data:image/png;base64,AA=='}]}),{type:'shot',index:0,checked:true});
assert.equal(shotProject.shots?.[0],true);
assert.equal(transition(shotProject,{type:'upload',files:[{name:'bath.png',url:'data:image/png;base64,AA=='}]}).shots?.[0],false);
const urlChanged=transition(seed[7],{type:'url',index:0,url:'https://example.com/post'});
assert.equal(urlChanged.stage,4);
assert.equal(urlChanged.channels[0],false);
assert.equal(urlChanged.channels[1],true);
assert.equal(transition(urlChanged,{type:'rollback',reason:'본문 수정'}).channelUrls?.[0],'https://example.com/post');
console.log('PASS · shot checklist reset, photo review gate, URL safety, recheck invalidation and compatible persistence');
const allDates=seed.map(p=>p.id===4?{...p,date:'2027-01-12'}:p);
assert.equal(scheduleRows(allDates).length,2);
assert.equal(boardColumns(allDates,'0','').reduce((n,c)=>n+c.projects.length,0),2);
assert.equal(scheduleRows(allDates,'2027-01-01','2027-01-31').length,1);
assert.equal(scheduleRows(allDates,'2026-09-04','2027-01-12').length,2);
assert.equal(scheduleRows(allDates,'','','박지훈').length,1);
assert.ok(metricDestinations.every(d=>d.view==='board'));
console.log('PASS · all-date scheduling, date/owner filters and consistent board metric destinations');
let sales=transition({...seed[2],stage:4},{type:'sales-scan'});
assert.equal(sales.salesReview?.scanned,true);
assert.throws(()=>transition(sales,{type:'sales-approve'}));
for(let index=0;index<4;index++)sales=transition(sales,{type:'sales-check',index,checked:true});
sales=transition(sales,{type:'sales-approve'});
assert.equal(sales.salesReview?.approved,true);
sales=transition(sales,{type:'sales-url',url:'https://item.gmarket.co.kr/demo'});
assert.equal(sales.salesReview?.approved,false);
assert.equal(sales.salesReview?.scanned,false);
assert.throws(()=>transition(sales,{type:'sales-url',url:'javascript:alert(1)'}));
assert.throws(()=>transition(seed[0],{type:'sales-scan'}));
assert.ok(validStored(seed.map(p=>p.id===sales.id?sales:p)));
assert.ok(!validStored(seed.map(p=>({...p,salesReview:{url:'javascript:x',scanned:true,checks:[true,true,true,true],approved:true}}))));
console.log('PASS · sales channel scan, human checks, approval invalidation, URL safety and persistence');

// 이전 버전 저장 데이터(시드 8건) 호환 · 새 시드 항목 병합 · 업로드 사진 수 일관성
const legacy=seed.slice(0,8);
assert.ok(validStored(legacy));
assert.ok(!validStored([]));
assert.ok(!validStored([...legacy,legacy[0]]));
assert.ok(!validStored([{...legacy[0],id:999}]));
const merged=mergeWithSeed(legacy.map(p=>p.id===1?{...p,note:'저장된 메모'}:p));
assert.equal(merged.length,seed.length);
assert.equal(merged.find(p=>p.id===1)?.note,'저장된 메모');
assert.ok(merged.some(p=>p.id===10));
const rolledBack=transition(seed.find(p=>p.id===2)!,{type:'rollback',reason:'재촬영'});
const firstUpload=transition(rolledBack,{type:'upload',files:[{name:'a.png',url:'data:image/png;base64,AAAA'}]});
assert.equal(firstUpload.photos,1);
const removedAll=transition(firstUpload,{type:'remove-uploads',indices:[0]});
assert.equal(removedAll.photos,0);
assert.throws(()=>transition(removedAll,{type:'advance'}),/사진을 먼저/);
console.log('PASS · legacy store compatibility, seed merge, upload photo count consistency');

// 선택 사진 일괄 분류
const twoUp=transition(rolledBack,{type:'upload',files:[{name:'a.png',url:'data:image/png;base64,AAAA'},{name:'b.png',url:'data:image/png;base64,BBBB'},{name:'c.png',url:'data:image/png;base64,CCCC'}]});
const bulk=transition(twoUp,{type:'photo-category-bulk',indices:[0,2],category:'객실'});
assert.deepEqual(bulk.uploads?.map(f=>f.category),['객실',undefined,'객실']);
assert.deepEqual(bulk.shots,[true,false,false,false]);
assert.equal(bulk.history?.[0],'2장 · 객실 일괄 분류');
assert.throws(()=>transition(twoUp,{type:'photo-category-bulk',indices:[5],category:'객실'}),/사진과 촬영 항목/);
assert.throws(()=>transition(twoUp,{type:'photo-category-bulk',indices:[0],category:'거실'}),/사진과 촬영 항목/);
console.log('PASS · bulk photo categorization');
