'use client';
import { useRef, useState } from 'react';
import { Download, Upload } from 'lucide-react';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { makeBackup, readBackup, backupLimit } from './backup-model';
import type { Project } from './projects';
export function DataTransfer({items,ready,onRestore}:{items:Project[];ready:boolean;onRestore:(items:Project[])=>boolean}){
 const input=useRef<HTMLInputElement>(null);
 const [pending,setPending]=useState<Project[]|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const download=()=>{try{const url=URL.createObjectURL(new Blob([makeBackup(items)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='stayflow-data-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('백업 다운로드를 요청했습니다. 다운로드 폴더에서 JSON 파일을 확인해 주세요.')}catch{setMessage('파일을 내보내지 못했습니다. 다시 시도해 주세요.')}};
 const choose=async(file?:File)=>{if(!file)return;setPending(null);setMessage('');setBusy(true);try{if(file.size>backupLimit)throw new Error('백업 파일은 4MB 이하로 선택해 주세요.');setPending(readBackup(await file.text()))}catch(e){setMessage(e instanceof Error?e.message:'파일을 읽지 못했습니다.')}finally{setBusy(false)}};
 return <section className="data-transfer"><div><strong>작업 데이터 옮기기</strong><p>사진·진행 상태·메모·게시 URL 포함. 백업 파일은 안전하게 보관해 주세요.</p></div><div className="transfer-actions"><button className="secondary-button" disabled={!ready||busy} onClick={download}><Download size={15}/>데이터 내보내기</button><button className="secondary-button" disabled={!ready||busy} onClick={()=>input.current?.click()}><Upload size={15}/>{busy?'파일 확인 중…':'데이터 불러오기'}</button><input ref={input} type="file" accept=".json,application/json" hidden onChange={e=>{void choose(e.target.files?.[0]);e.target.value=''}}/></div>{message&&<p className="transfer-message" role="status">{message}</p>}<AlertDialog open={!!pending} onOpenChange={open=>{if(!open)setPending(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>현재 작업 데이터를 바꿀까요?</AlertDialogTitle><AlertDialogDescription>백업의 {pending?.length}개 콘텐츠로 이 브라우저의 전체 작업 데이터를 교체합니다. 현재 데이터를 보관하려면 취소 후 먼저 내보내세요. 외부 게시물은 변경하지 않습니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel><AlertDialogAction onClick={()=>{if(pending&&onRestore(pending)){setPending(null);setMessage('백업 데이터를 불러왔습니다. 사진과 진행 상태가 복원되었습니다.')}else{setPending(null);setMessage('브라우저 저장에 실패해 불러오기를 취소했습니다. 기존 데이터는 유지됩니다.')}}}>확인 · 데이터 교체</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>
}
