'use client';
import { useState } from 'react';
import { Camera, CalendarDays, Upload, Sparkles, Check, ArrowRight, RotateCcw, Globe, FileText, LoaderCircle, CircleAlert, CheckCheck, ExternalLink, ChevronLeft, ChevronRight, Maximize2, Trash2 } from 'lucide-react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { SalesChannelReview } from './sales-channel-review';
import { ShotChecklist, PhotoReviews, ChannelUrl } from './quality-tools';
import { ImageComparison } from './image-comparison';
import { AxPanel } from './ax-panel';
import { stages, photoList, shotNames, type Project, type Action } from './projects';
import { visiblePhotoSelection, togglePhotoSelection } from './photo-selection-model';
import { defaultDetailTab } from './board-model';
export function Detail({project:p,onClose,onAction:dispatch,all,inline=false}:{project:Project;onClose:()=>void;onAction:(action:Action)=>boolean;all:Project[];inline?:boolean}){
 const [rollbackOpen,setRollbackOpen]=useState(false),[rollbackReason,setRollbackReason]=useState('');
 const [tab,setTab]=useState<string>(defaultDetailTab(p.stage));
 const [date,setDate]=useState(p.date),[time,setTime]=useState(p.time),[due,setDue]=useState(p.due),[owner,setOwner]=useState(p.owner);
 const [note,setNote]=useState(p.note),[analysis,setAnalysis]=useState<'idle'|'loading'|'done'>('idle'),[error,setError]=useState(''),[uploading,setUploading]=useState(false);
 const [preview,setPreview]=useState<number|null>(null);
 const [selectedPhotos,setSelectedPhotos]=useState<number[]>([]),[deleteOpen,setDeleteOpen]=useState(false);
 const photos=photoList(p);
 const [comparisonIndex,setComparisonIndex]=useState<number|null>(null);
 const [onlyPending,setOnlyPending]=useState(false);
 const [adjustments,setAdjustments]=useState<Record<number,{brightness:number;contrast:number}>>({});
 const activeIndex=visiblePhotoSelection(p,comparisonIndex,onlyPending);
 const activePhoto=activeIndex===null?undefined:photos[activeIndex];
 const selectPhoto=(index:number)=>{if(onlyPending&&!p.photoReviews?.some(r=>r.index===index&&!r.resolved))setOnlyPending(false);setComparisonIndex(togglePhotoSelection(activeIndex,index))};
 const filterPending=(value:boolean)=>{setOnlyPending(value);setComparisonIndex(visiblePhotoSelection(p,comparisonIndex,value))};
 const onAction=(action:Action)=>{if(action.type==='reject'&&!action.note.trim()){setError('수정 요청 사유를 입력해 주세요.');return false}if(action.type==='advance'&&p.stage===1){const unclassified=p.uploads?.filter(f=>!f.category).length??0;if(unclassified){setError(`촬영 항목이 지정되지 않은 사진이 ${unclassified}장 있습니다. 모든 사진을 분류해 주세요.`);return false}const missing=shotNames.filter((_,i)=>!p.shots?.[i]);if(missing.length){setError(`필수 촬영 컷 미확인: ${missing.join(' · ')}. 모두 확인한 뒤 보정을 시작해 주세요.`);return false}}const ok=dispatch(action);if(ok&&action.type==='photo-review'&&action.resolved&&comparisonIndex===action.index)setComparisonIndex(null);if(ok&&(action.type==='remove-uploads'||action.type==='upload')){setComparisonIndex(null);setAdjustments({})}setError(ok?'':action.type==='schedule'?'촬영일과 마감일을 확인해 주세요. 마감일은 촬영일보다 빠를 수 없습니다.':'현재 단계에서 처리할 수 없습니다. 입력 내용을 확인해 주세요.');return ok};
 const saveSchedule=()=>{if(all.some(x=>x.id!==p.id&&x.stage===0&&x.owner===owner&&x.date===date&&x.time===time)){setError('같은 담당자의 촬영 일정과 시간이 겹칩니다. 다른 시간을 선택해 주세요.');return}setError('');onAction({type:'schedule',date,time,due,owner})};
 const upload=async(files:FileList|null)=>{if(!files?.length)return;setError('');const selected=Array.from(files);if(selected.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type))){setError('JPG, PNG, WebP 사진만 선택해 주세요.');return}if(selected.some(f=>f.size>1024*1024)){setError('사진 한 장은 1MB 이하로 선택해 주세요.');return}const total=all.reduce((n,x)=>n+(x.uploads??[]).reduce((s,f)=>s+f.url.length,0),0);if(total+selected.reduce((n,f)=>n+f.size*1.4,0)>2500000){setError('데모 사진 저장 한도(약 2MB)를 초과했습니다. 더 작은 사진을 선택해 주세요.');return}setUploading(true);try{const data=await Promise.all(selected.map(f=>new Promise<{name:string;url:string}>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:f.name,url:String(reader.result)});reader.onerror=reject;reader.readAsDataURL(f)})));onAction({type:'upload',files:data})}catch{setError('사진을 읽지 못했습니다. 다시 선택해 주세요.')}finally{setUploading(false)}};
 const content=<><SheetHeader className="detail-header"><span className="eyebrow">CONTENT / ST-{String(p.id).padStart(3,'0')}</span>{inline?<h2 className="detail-title">{p.name}</h2>:<SheetTitle className="detail-title">{p.name}</SheetTitle>}{inline?<p className="inline-description">{p.region} · {p.type} <span className={`status s${p.stage}`}>{stages[p.stage]}</span></p>:<SheetDescription>{p.region} · {p.type} <span className={`status s${p.stage}`}>{stages[p.stage]}</span></SheetDescription>}</SheetHeader><div className="detail-steps">{stages.map((s,i)=><span key={s} className={i===p.stage?'current':i<p.stage?'passed':''}><b>{i<p.stage?<Check size={12}/>:i+1}</b>{s}</span>)}</div>
 {p.stage>0&&<section className="rollback-section"><button type="button" className="secondary-button" aria-expanded={rollbackOpen} onClick={()=>setRollbackOpen(!rollbackOpen)}><RotateCcw size={15}/>이전 단계로 되돌리기</button>{rollbackOpen&&<form className="rollback-form" onSubmit={e=>{e.preventDefault();if(!rollbackReason.trim())return;const previous=p.stage-1;if(onAction({type:'rollback',reason:rollbackReason})){setRollbackOpen(false);setRollbackReason('');setTab(defaultDetailTab(previous));setAnalysis('idle')}}}><strong>{stages[p.stage]} → {stages[p.stage-1]}</strong><p>사진, 일정, 입력 정보는 유지됩니다. 되돌리는 사유는 작업 기록에 남습니다.</p>{p.stage>=4&&<p className="revision-note">모든 채널의 게시 완료 표시가 초기화됩니다. 실제 외부 게시물은 삭제되지 않으므로 수정 후 다시 확인해 주세요.</p>}<label>되돌리는 사유<textarea required maxLength={500} value={rollbackReason} onChange={e=>setRollbackReason(e.target.value)} placeholder="예: 누락된 욕실 사진을 추가해야 합니다."/></label><div className="rollback-buttons"><button type="button" className="secondary-button" onClick={()=>{setRollbackOpen(false);setRollbackReason('')}}>취소</button><button type="submit" className="primary-button" disabled={!rollbackReason.trim()||uploading}>확인 · 이전 단계로 이동</button></div></form>}</section>}
 <AxPanel project={p} all={all}/>
 <Tabs value={tab} onValueChange={v=>{setTab(String(v));setError('')}} className={inline?"detail-tabs inline-tabs":"detail-tabs"}><TabsList variant="line"><TabsTrigger value="schedule"><CalendarDays/>촬영·정보</TabsTrigger><TabsTrigger value="photos"><Camera/>사진·검수</TabsTrigger><TabsTrigger value="channels"><Globe/>채널 게시</TabsTrigger></TabsList>
 <TabsContent value="schedule"><section className="detail-section"><h3>촬영 일정</h3><div className="form-grid"><label>촬영일<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>촬영 시간<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>담당자<Select value={owner} onValueChange={v=>v&&setOwner(v)}><SelectTrigger className="owner-select"><SelectValue/></SelectTrigger><SelectContent>{['김서연','박지훈','이수민'].map(n=><SelectItem value={n} key={n}>{n}</SelectItem>)}</SelectContent></Select></label><label>최종 마감일<input type="date" value={due} min={date} onChange={e=>setDue(e.target.value)}/></label></div><button className="secondary-button" onClick={saveSchedule}>일정 저장</button></section><section className="detail-section brief"><h3>촬영 브리프</h3><p>공간 전체, 객실, 욕실, 외관, 주요 편의시설을 촬영합니다. 공간의 동선과 자연광을 중심으로 기록해 주세요.</p><div className="brief-tags"><span>가로형 대표 컷</span><span>공간별 디테일</span><span>인물 없는 사진</span></div></section>{p.stage===0&&<button className="primary-button full" onClick={()=>{if(onAction({type:'advance'}))setTab('photos')}}><CheckCheck size={17}/>촬영 완료 · 사진 업로드로 이동<ArrowRight size={17}/></button>}<section className="detail-section"><h3>작업 기록</h3>{(p.history?.length?p.history:['콘텐츠 제작 프로젝트 등록']).map((h,i)=><div className="history-item" key={i}><i/>{h}</div>)}</section></TabsContent>
 <TabsContent value="photos">{p.stage>=1&&<ShotChecklist project={p} onAction={onAction}/>}<section className="detail-section"><div className="section-title"><h3>사진 라이브러리 <span className="count">{p.photos}장</span></h3><span className="muted">{p.uploads?.length?'내 브라우저에 저장':'참고용 샘플 사진'}</span></div>{p.stage===1?<label className="upload-box"><Upload size={24}/><strong>{uploading?'사진을 불러오는 중…':'클릭하여 촬영 사진 추가'}</strong><span>JPG, PNG, WebP · 장당 1MB 이하</span><small>서버 전송 없이 이 브라우저에만 저장됩니다.</small><input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={uploading} onChange={e=>{void upload(e.target.files);e.target.value=''}}/></label>:null}{p.photos===0?<div className="empty-message">{p.stage===0?'촬영을 완료한 후 사진을 추가할 수 있습니다.':'아직 등록된 사진이 없습니다.'}</div>:<>{p.stage===1&&p.uploads?.length&&<div className="photo-selection-bar"><span><strong>{selectedPhotos.length}</strong> / {photos.length}장 선택</span><div className="photo-selection-actions"><button type="button" className="secondary-button" onClick={()=>setSelectedPhotos(selectedPhotos.length===photos.length?[]:photos.map((_,i)=>i))}>{selectedPhotos.length===photos.length?'선택 해제':'전체 선택'}</button><button type="button" className="photo-bulk-delete" disabled={!selectedPhotos.length} onClick={()=>setDeleteOpen(true)}><Trash2 size={15}/>선택 삭제</button></div></div>}<div className="photo-strip">{photos.map((f,i)=><figure key={i} className={selectedPhotos.includes(i)?'is-selected':''}>{p.stage===1&&p.uploads?.[i]&&<span className="photo-select-check"><Checkbox checked={selectedPhotos.includes(i)} onCheckedChange={checked=>setSelectedPhotos(current=>checked===true?[...new Set([...current,i])]:current.filter(index=>index!==i))} aria-label={`${f.name} 선택`}/></span>}<button type="button" className="photo-preview-trigger" onClick={()=>setPreview(i)} aria-label={`${f.name} 크게 보기`}><img src={f.url} alt={f.name}/><span><Maximize2 size={15}/>크게 보기</span></button><figcaption>{f.name}</figcaption>{p.stage>=2&&<button type="button" className="secondary-button" aria-pressed={activeIndex===i} onClick={()=>selectPhoto(i)}>{activeIndex===i?'수정 중':'수정 선택'}</button>}</figure>)}</div>{!p.uploads?.length&&<p className="fineprint">전체 장수는 더미 데이터입니다. 아래 3장은 가상 숙소와 무관한 참고 사진입니다.</p>}</>}
 {p.stage===1&&p.uploads?.length&&<div className="photo-category-grid">{p.uploads.map((f,i)=><label key={i}><span>{f.name}</span><Select value={f.category??'unclassified'} onValueChange={value=>value&&value!=='unclassified'&&onAction({type:'photo-category',index:i,category:value})}><SelectTrigger aria-label={`${f.name} 촬영 항목`}><SelectValue>{f.category??'미분류 · 항목 선택'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="unclassified" disabled>미분류 · 항목 선택</SelectItem>{shotNames.map(name=><SelectItem value={name} key={name}>{name}</SelectItem>)}</SelectContent></Select></label>)}</div>}
 {p.stage===1&&<AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{selectedPhotos.length===photos.length?'업로드한 사진을 모두 삭제할까요?':`선택한 사진 ${selectedPhotos.length}장을 삭제할까요?`}</AlertDialogTitle><AlertDialogDescription>선택한 사진이 이 브라우저의 작업 데이터에서 삭제됩니다. 삭제 후 필수 촬영 컷을 다시 확인해 주세요.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel onClick={()=>setDeleteOpen(false)}>취소</AlertDialogCancel><AlertDialogAction className="photo-delete-confirm" onClick={()=>{if(onAction({type:'remove-uploads',indices:selectedPhotos})){setSelectedPhotos([]);setPreview(null);setDeleteOpen(false)}}}>선택한 {selectedPhotos.length}장 삭제</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
 {p.stage===1&&<button className="primary-button full" disabled={!p.photos||uploading} onClick={()=>onAction({type:'advance'})}>사진 업로드 완료 · 보정 시작<ArrowRight size={17}/></button>}</section>
 {p.stage>=2&&<><PhotoReviews project={p} onAction={onAction} selectedIndex={activeIndex} onSelect={selectPhoto} onlyPending={onlyPending} onFilter={filterPending}/><section className="detail-section"><h3>보정 전·후 비교 <span className="demo-pill">선택 사진 미리보기</span></h3>{activePhoto&&activeIndex!==null?<><p role="status">수정 중: {activePhoto.category??'미분류'} · {activePhoto.name} ({activeIndex+1} / {photos.length})</p><ImageComparison key={p.id+':'+activeIndex+':'+activePhoto.url} src={activePhoto.url} name={activePhoto.name} adjustment={adjustments[activeIndex]??{brightness:100,contrast:100}} onAdjust={value=>setAdjustments(current=>({...current,[activeIndex]:value}))}/></>:<p className="empty-message">수정할 사진을 선택해 주세요. 선택한 사진을 다시 누르면 해제됩니다.</p>}<p className="fineprint">조절값은 이 숙소 화면에서 사진별로 미리보기에만 적용됩니다. 화면을 닫거나 새로고침하면 초기화되며 원본 파일·게시 사진에는 저장되지 않습니다.</p></section>
 <section className="ai-panel"><div className="section-title"><h3><Sparkles size={17}/>AI 사전 검수 <span className="demo-pill">시뮬레이션</span></h3><button className="secondary-button" disabled={analysis==='loading'} onClick={()=>{setAnalysis('loading');setTimeout(()=>setAnalysis('done'),1200)}}>{analysis==='loading'?<LoaderCircle className="spin" size={15}/>:<Sparkles size={15}/>} {analysis==='done'?'다시 실행':'검사 실행'}</button></div>{analysis==='done'?<div aria-live="polite"><div className="ai-result"><CircleAlert size={17}/><div><strong>밝은 창가 영역 · 노출 확인 필요</strong><p>하이라이트 손실 가능성을 검수자가 확인하는 예시입니다.</p></div></div><div className="ai-result good"><Check size={17}/><div><strong>공간 자동 태그 제안</strong><p>객실 · 거실 · 오션뷰</p></div></div><p className="fineprint">미리 준비된 예시 결과입니다. 업로드한 사진을 실제로 분석하지 않습니다.</p></div>:<p className="ai-description">흐림·노출·중복 여부를 AI가 먼저 점검하고, 담당자는 확인이 필요한 사진에 집중합니다. 최종 승인은 사람이 결정합니다.</p>}</section>
 {p.note&&<div className="revision-note"><strong>수정 요청 사항</strong><p>{p.note}</p></div>}{p.stage===2&&<button className="primary-button full" onClick={()=>onAction({type:'advance'})}>보정 완료 · 검수 요청<ArrowRight size={17}/></button>}{p.stage===3&&<section className="review-actions"><label>검수 의견<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="예: 창가 영역의 노출을 낮춰 주세요. 수정 요청 시 필수입니다."/></label><div><button className="secondary-button" onClick={()=>onAction({type:'reject',note})}><RotateCcw size={16}/>수정 요청</button><button className="primary-button" onClick={()=>{if(onAction({type:'advance'}))setTab('channels')}}><Check size={17}/>검수 승인 · 게시 준비</button></div></section>}</>}
 </TabsContent><TabsContent value="channels"><SalesChannelReview project={p} onAction={onAction}/><section className="detail-section marketing-section"><h3>마케팅 채널 게시 체크리스트</h3><p className="section-copy">사이트를 새 탭에서 열어 게시물을 확인한 뒤, 돌아와 게시 완료로 표시해 주세요.</p>{p.stage<4&&<div className="revision-note">검수를 승인하면 게시 상태를 변경할 수 있습니다.</div>}{[{name:'자사 웹사이트',spec:'대표 이미지 · 숙소 소개',url:'https://example.com/',hint:'테스트 주소 · 실제 자사 사이트 아님',icon:Globe},{name:'인스타그램',spec:'피드 이미지 · 캡션',url:'https://www.instagram.com/',hint:'서비스 홈 · 로그인 필요할 수 있음',icon:Camera},{name:'네이버 블로그',spec:'본문 이미지 · 숙소 정보',url:'https://blog.naver.com/',hint:'서비스 홈 · 로그인 필요할 수 있음',icon:FileText}].map((c,i)=><div className="channel-item" key={c.name}><span className="channel-icon"><c.icon size={22}/></span><div className="channel-info"><a className="channel-name" href={p.channelUrls?.[i]||c.url} target="_blank" rel="noopener noreferrer" aria-label={`${c.name} 새 탭에서 열기`}>{c.name}</a><p>{c.spec}</p><small>{p.channelUrls?.[i]?'저장된 게시물 주소로 연결':c.hint}</small></div><div className="channel-actions"><a className="secondary-button channel-link" href={p.channelUrls?.[i]||c.url} target="_blank" rel="noopener noreferrer" aria-label={`${c.name} 사이트 열기 (새 탭)`}>사이트 열기<ExternalLink size={14}/></a><button className={p.channels[i]?'channel-done':'secondary-button'} disabled={p.stage<4} onClick={()=>onAction({type:'channel',index:i})}>{p.channels[i]?<><Check size={15}/>게시 완료 · 취소</>:'게시 완료로 표시'}</button></div><ChannelUrl project={p} index={i} onAction={onAction}/></div>)}<div className="channel-summary"><strong>{p.channels.filter(Boolean).length} / 3 채널 완료</strong><span>{p.stage===5?'모든 채널 게시가 완료되었습니다.':'모든 채널을 완료하면 제작이 종료됩니다.'}</span></div><p className="fineprint">URL을 저장하면 해당 게시물로 연결됩니다. 미입력 시 테스트용 사이트 또는 서비스 홈으로 연결됩니다. 실제 게시·게시 여부 자동 확인은 하지 않으며, 완료 표시는 데모 체크리스트에만 저장됩니다.</p></section></TabsContent></Tabs>
 {error&&<div className="form-error" role="alert">{error}</div>}{preview!==null&&photos[preview]&&<Dialog open onOpenChange={open=>!open&&setPreview(null)}><DialogContent className="photo-preview-dialog"><DialogTitle>{photos[preview].category??'미분류'} · {photos[preview].name}</DialogTitle><DialogDescription>{preview+1} / {photos.length} · 사진을 확대해 확인합니다.</DialogDescription><div className="photo-preview-stage"><img src={photos[preview].url} alt={`${photos[preview].category??'미분류'} ${photos[preview].name} 확대 보기`}/>{photos.length>1&&<><button type="button" className="photo-preview-nav previous" aria-label="이전 사진" onClick={()=>setPreview((preview-1+photos.length)%photos.length)}><ChevronLeft/></button><button type="button" className="photo-preview-nav next" aria-label="다음 사진" onClick={()=>setPreview((preview+1)%photos.length)}><ChevronRight/></button></>}</div></DialogContent></Dialog>}</>;
 return inline?<div className="inline-detail">{content}</div>:<Sheet open onOpenChange={o=>!o&&onClose()}><SheetContent className="detail-sheet">{content}</SheetContent></Sheet>
}
