'use client';
import { useState, useEffect, useRef } from 'react';
import { flushSync } from 'react-dom';
import { LayoutDashboard, Columns3, Camera, ArrowUpRight, ArrowRight, Sparkles, CalendarDays, Clock3, CheckCheck, CircleAlert, FolderOpen, MapPin, MessageSquareWarning } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from '@/components/ui/sidebar';
import { seed, stages, images, transition, validStored, type Project, type Action } from './projects';
import { DataTransfer } from './data-transfer';
import { AxGuide } from './quality-tools';
import { axDashboardSummary } from './ax-model';
import { Bot } from 'lucide-react';
import { Detail } from './detail';
import { ContentBoard } from './content-board';
import { ScheduleWorkspace } from './schedule-workspace';
import { StageWorkspace } from './stage-workspace';
import { workspaceViews, workspaceQueue, isWorkspaceView, workspaceForStage, metricDestinations } from './workspace-model';
function Status({stage}:{stage:number}) {return <span className={`status s${stage}`}><i/>{stages[stage]}</span>}
type NavState={stayflow:true;view:string;selected:number|null;focusTask:number|null;filter:string;queueScope:string;query:string};
export default function Home(){
 const [view,setView]=useState('dashboard');
 const [items,setItems]=useState(seed);
 const [selected,setSelected]=useState<number|null>(null);
 const [focusTask,setFocusTask]=useState<number|null>(null);
 const [filter,setFilter]=useState('all');
 const [queueScope,setQueueScope]=useState('all');
 const [query,setQuery]=useState('');
 const [message,setMessage]=useState('');
 const itemsRef=useRef(items);itemsRef.current=items;
 const [ready,setReady]=useState(false);
 const commitRef=useRef<(id:number,a:Action)=>boolean>(()=>false);
 const navState=(changes:Partial<NavState>={}):NavState=>({stayflow:true,view,selected,focusTask,filter,queueScope,query,...changes});
 const applyNav=(next:NavState)=>{setView(next.view);setSelected(next.selected);setFocusTask(next.focusTask);setFilter(next.filter);setQueueScope(next.queueScope);setQuery(next.query)};
 const pushNav=(changes:Partial<NavState>)=>{const next=navState(changes);window.history.pushState(next,'');applyNav(next);if(next.view!==view)window.scrollTo({top:0})};
 useEffect(()=>{try{const raw=localStorage.getItem('stayflow-v1');if(raw){const saved:unknown=JSON.parse(raw);if(validStored(saved)){const migrated=(saved as Project[]).map(project=>({...project,cover:seed.find(item=>item.id===project.id)?.cover??project.cover}));setItems(migrated);localStorage.setItem('stayflow-v1',JSON.stringify(migrated))}else setMessage('저장된 데이터 형식을 확인할 수 없어 기본 데모를 표시합니다.')}}catch{setMessage('브라우저 저장을 사용할 수 없습니다. 이번 화면에서만 변경됩니다.')}setReady(true)},[]);
 useEffect(()=>{window.history.replaceState(navState(),'');const onPop=(event:PopStateEvent)=>{const next=event.state as NavState|null;if(next?.stayflow)applyNav(next)};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);
 useEffect(()=>{if(!message)return;const timer=window.setTimeout(()=>setMessage(''),3500);return()=>window.clearTimeout(timer)},[message]);
 const commit=(id:number,a:Action)=>{try{const p=itemsRef.current.find(x=>x.id===id);if(!p)throw new Error('콘텐츠를 찾을 수 없습니다.');const result=transition(p,a);const next=itemsRef.current.map(x=>x.id===id?result:x);let saved=true;try{localStorage.setItem('stayflow-v1',JSON.stringify(next))}catch{saved=false}itemsRef.current=next;setItems(next);setMessage(saved?`${p.name} · ${result.history?.[0]} · 저장됨`:'변경되었습니다. 브라우저 저장에 실패해 새로고침하면 복원되지 않습니다.');return true}catch(e){setMessage(e instanceof Error?e.message:'처리하지 못했습니다.');return false}};
 commitRef.current=commit;
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:unknown)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};register({name:'get_content_pipeline',description:'Read content project IDs, stages and deadlines from the current local demo.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>itemsRef.current.map(p=>({id:p.id,name:p.name,stage:stages[p.stage],due:p.due}))});register({name:'approve_content_review',description:'Approve a project currently awaiting review and move it to channel publishing. Changes browser-local demo state only.',inputSchema:{type:'object',properties:{id:{type:'integer'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const id=(input as {id?:unknown})?.id;if(typeof id!=='number'||!Number.isInteger(id))throw new Error('A valid integer project ID is required.');const p=itemsRef.current.find(x=>x.id===id);if(!p||p.stage!==3)throw new Error('Project must be awaiting review.');let success=false;flushSync(()=>{success=commitRef.current(id,{type:'advance'})});if(!success)throw new Error('Approval failed.');return {id,stage:'채널 게시'}}});return()=>lifecycle.abort()},[]);
 const navigate=(target:string,id?:number,scope='all')=>pushNav({queueScope:scope,focusTask:id??null,view:target,selected:null,filter:'all',query:''});
 const workspace=isWorkspaceView(view)?view:view==='revisions'?'review':null;
 const title=view==='revisions'?'수정사항':workspace?workspaceViews[workspace].title:view==='board'?'전체 콘텐츠 보드':'대시보드';
 const counts=stages.map((_,i)=>items.filter(p=>p.stage===i).length);
 const open=(p:Project)=>pushNav({selected:p.id});
 const showBoard=(stage='all')=>pushNav({filter:stage,query:'',view:'board',selected:null,focusTask:null,queueScope:'all'});
 const openMetric=(index:number)=>{const d=metricDestinations[index];if(d.view==='board')showBoard(d.scope);else navigate(d.view,undefined,d.scope)};
 const advanceFromBoard=(p:Project)=>{if(commit(p.id,{type:'advance'}))pushNav({filter:'all',selected:p.id})};
 return <SidebarProvider style={{'--sidebar-width':'232px'} as React.CSSProperties}>
 <Sidebar><SidebarHeader className="brand"><span className="brand-icon"><Columns3 size={24}/></span><strong>stayflow<span>CONTENT WORKSPACE</span></strong></SidebarHeader><SidebarContent className="nav-body"><div className="workspace-label">WORKSPACE</div><SidebarMenu>{[{key:'dashboard',label:'대시보드',icon:LayoutDashboard},{key:'board',label:'전체 콘텐츠 보드',icon:Columns3},{key:'revisions',label:'수정사항',icon:MessageSquareWarning}].map(n=><SidebarMenuItem key={n.key}><SidebarMenuButton className="nav-item" isActive={view===n.key} onClick={()=>n.key==='board'?showBoard():pushNav({view:n.key,selected:null,focusTask:null,filter:'all',query:'',queueScope:n.key==='revisions'?'revision':'all'})}><n.icon/><span>{n.label}</span>{n.key==='board'&&<small>{items.length}</small>}{n.key==='revisions'&&<small>{workspaceQueue(items,'review','revision').length}</small>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="workspace-label pipeline-label">제작 파이프라인</div><SidebarMenu>{Object.entries(workspaceViews).map(([key,config])=><SidebarMenuItem key={key}><SidebarMenuButton className="nav-item stage-nav" isActive={view===key} onClick={()=>navigate(key)}><span className="nav-step">{config.step}</span><span>{config.title}</span><small>{isWorkspaceView(key)?workspaceQueue(items,key).length:0}</small></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="nav-note"><span className="live-dot"/> 콘텐츠팀 워크스페이스<p>촬영부터 발행까지<br/>흐름이 보이는 작업 공간</p></div></SidebarContent><SidebarFooter className="nav-bottom"><div className="demo-tag">PROTOTYPE <span>v1.0</span></div><p>가상 데이터 · 실제 게시 없음</p><div className="profile"><span className="avatar">서</span><div><strong>김서연</strong><small>콘텐츠 매니저 · 데모</small></div></div></SidebarFooter></Sidebar>
 <main className="app-main"><header className="topbar"><div><SidebarTrigger/><span>워크스페이스</span><span className="slash">/</span><b>{title}</b></div><div className="top-date"><CalendarDays size={16}/>2026년 9월 4일, 금요일<span className="demo-pill">데모 기준일</span></div></header>
 <div className="page"><div className="page-heading"><div><div className="eyebrow">CONTENT OPERATIONS</div><h1>{view==='dashboard'?'오늘의 콘텐츠 흐름':title}<span className="heading-dot">.</span></h1><p>{workspace?workspaceViews[workspace].description:'촬영부터 채널 게시까지, 다음 할 일을 명확하게.'}</p></div><span className="team-badge"><span className="avatar tiny">서</span><span className="avatar tiny blue">지</span><span className="avatar tiny pink">수</span><span>콘텐츠팀</span></span></div>
 <DataTransfer items={items} ready={ready} onRestore={next=>{try{if(!validStored(next))return false;localStorage.setItem('stayflow-v1',JSON.stringify(next));itemsRef.current=next;setItems(next);pushNav({selected:null,focusTask:null,view:'board',filter:'all',query:'',queueScope:'all'});setMessage('백업 데이터 복원 완료 · 저장됨');return true}catch{return false}}}/>
 {!workspace&&<div className="metrics">{[{label:'진행 중 콘텐츠',value:items.filter(p=>p.stage<5).length,sub:'완료 제외 · 제작 중인 콘텐츠',icon:FolderOpen},{label:'촬영 예정',value:items.filter(p=>p.stage===0).length,sub:'모든 날짜의 촬영 예정',icon:Camera},{label:'검수 대기',value:counts[3],sub:'승인하면 게시 단계로 이동',icon:CheckCheck},{label:'마감 지연',value:items.filter(p=>p.stage<5&&p.due<'2026-09-04').length,sub:'우선 확인이 필요합니다',icon:Clock3},{label:'완료 콘텐츠',value:counts[5],sub:`전체 ${items.length}건 중 ${counts[5]}건 완료`,icon:CheckCheck}].map((m,i)=><button type="button" className={`metric metric-${i}`} key={m.label} onClick={()=>openMetric(i)} aria-pressed={view==='board'&&filter===metricDestinations[i].scope} aria-label={`${m.label} ${m.value}건 보기`}><div>{m.label}<m.icon size={19}/></div><strong>{m.value}<small>건</small></strong><p>{i===3&&<span className="warning-dot"/>}{m.sub}<ArrowUpRight className="metric-link-icon" size={15}/></p></button>)}</div>}
 {view==='dashboard'?<><section className="attention"><div className="spark-icon"><Sparkles size={22}/></div><div><h2>지금 확인하면, 다음 작업이 빨라집니다 <span>AX ASSIST</span></h2><p>검수 대기 {counts[3]}건을 먼저 확인해 보세요. 승인 후 채널 게시를 시작할 수 있습니다.</p></div><button onClick={()=>navigate('review',undefined,'3')}>검수 확인하기 <ArrowRight size={17}/></button></section>
 <section className="ax-stats" aria-label="AX 자동화 현황"><div className="ax-stats-head"><Bot size={15}/><strong>AI·자동화가 지금 처리할 수 있는 일</strong><span className="demo-pill">시뮬레이션</span></div><div className="ax-stats-grid">{axDashboardSummary(items).map(t=><button key={t.label} onClick={()=>navigate(t.view)}><span>{t.label}</span><strong>{t.value}<small>{t.unit}</small></strong><small>{t.hint}</small></button>)}</div></section>
 <div className="dashboard-grid"><section className="panel"><div className="section-title"><h2>제작 파이프라인</h2><button className="text-button" onClick={()=>showBoard()}>전체 보기 <ArrowUpRight size={16}/></button></div><div className="pipeline">{stages.map((s,i)=><button onClick={()=>navigate(workspaceForStage(i),undefined,String(i))} className={`pipe pipe-${i}`} key={s}><div><span className={`stage-dot dot-${i}`}/><span>{s}</span></div><strong>{counts[i]}<small>건</small></strong><div className="pipe-track"><span style={{width:`${Math.max(12,counts[i]/items.length*100)}%`}}/></div></button>)}</div><div className="panel-caption"><CircleAlert size={15}/>각 단계를 선택해 해당 콘텐츠를 확인하세요.</div></section>
 <section className="panel schedule"><div className="section-title"><h2>오늘의 촬영 <span className="count">{items.filter(p=>p.stage===0&&p.date==='2026-09-04').length}</span></h2><span className="muted">9월 4일</span></div>{items.filter(p=>p.stage===0&&p.date==='2026-09-04').map(p=><button className="schedule-item" key={p.id} onClick={()=>navigate('schedule',p.id,'today')}><div className="schedule-time">{p.time}<small>촬영 예정</small></div><div><strong>{p.name}</strong><p><MapPin size={13}/>{p.region}</p></div><span className="avatar tiny blue">{p.owner[1]}</span></button>)}</section></div>
 <section className="work-section"><div className="section-title"><div><h2>우선 확인할 콘텐츠</h2><p>마감과 다음 작업을 함께 확인하세요.</p></div><button className="text-button" onClick={()=>showBoard()}>콘텐츠 보드 열기 <ArrowRight size={16}/></button></div><div className="project-grid">{items.filter(p=>p.stage===3||p.stage===4).slice(0,3).map(p=><button className="project-card" key={p.id} onClick={()=>navigate(workspaceForStage(p.stage),p.id)}><div className="card-image"><img src={images[p.cover]} alt={`${p.name} 참고용 숙소 사진`}/><Status stage={p.stage}/>{p.due<'2026-09-04'&&<span className="late-badge">마감 지연</span>}</div><div className="card-body"><div className="card-meta">{p.region}<span>{p.type}</span></div><h3>{p.name}<ArrowUpRight size={18}/></h3><div className="card-detail"><span><Camera size={15}/>{p.photos}장</span><span><CalendarDays size={15}/>{p.due.slice(5).replace('-','.')} 마감</span></div><footer><span><span className="avatar tiny">{p.owner[1]}</span>{p.owner}</span><span>{p.stage===3?'보정본 검수하기':'채널 게시하기'} <ArrowRight size={14}/></span></footer></div></button>)}</div></section></>:view==='board'?<ContentBoard items={items} filter={filter} query={query} onFilter={setFilter} onQuery={setQuery} onClear={()=>{setFilter('all');setQuery('')}} onOpen={open} onAdvance={advanceFromBoard}/>:workspace==='schedule'?<ScheduleWorkspace key={focusTask??'schedule'} items={items} initialProjectId={focusTask} onAction={commit}/>:workspace?<StageWorkspace key={`${workspace}-${focusTask??'queue'}-${queueScope}`} scope={queueScope} initialProjectId={focusTask} view={workspace} items={items} onAction={commit} onNavigate={navigate}/>:null}
 <AxGuide key={view}/><footer className="page-footer"><span><span className="live-dot"/>STAYFLOW · CONTENT WORKSPACE</span><span>가상 숙소 데이터 · AI 및 채널 게시 시뮬레이션</span></footer></div>{message&&<div className="save-toast" role="status">{message}</div>}</main>{selected!==null&&items.find(p=>p.id===selected)&&<Detail key={selected} project={items.find(p=>p.id===selected)!} all={items} onClose={()=>window.history.back()} onAction={a=>commit(selected,a)}/>}</SidebarProvider>
}
